### ISSUE TITLE
Review #2

### ISSUE THREAD

**Issue by ShkiTTer** [enzhdanova/task1_calc#1]
1. `fun Title(@StringRes titleText: Int, modifier: Modifier)` - `modifier` можно сделать необязательным параметром. В целом так и принято делать в Compose
2. `private fun displayCalcPreview()` - названия Composable методов должны начинаться с заглавной буквы.
3. `fun ButtonCalc(contentText: String, modifier: Modifier, backgroundColor: Color, textColor: Color, onClick: () -> Unit)` - для задания цветов кнопки лучше использовать специальный объект - `[ButtonColors]`. С помощью него можно настроить цвета самой кнопки и ее контента. Таким образом у элемента `Text` не надо будет устанавливать `textColor`
4. `Type.kt` - полученные шрифты лучше сделать приватными, чтобы не торчали наружу, а использовались именно стили из темы
5. `Calculator ` - для математических операций лучше сравнивать именно элементы enum'a, а не просто строковые символы.
6. Старайся следить за форматированием кода, по всюду съехавшие переносы, пробелы и так - сильно портит общее качество кода

**Comment by enzhdanova** [comment]
1. Сделала везде modifier не обязательным
2. Взяла на заметку, сделала так же сразу по умолчанию значение `buttonColors: ButtonColors`, нормально же?

Остальное: исправила
